version: '3'

services:
    web:
        build: ./
        command: sh -c 'npm install && node src/servidor.js'
        ports:
            - '3000:3000'
        volumes:
        - ./api:/api
        links:
        - "db:redis-contenedor"


    db:
        image: redis
        ports:
        - "6380:6379"