version: '3'

services:
    web:
        build: ./
        ports: 
            - '5000:5000'
        volumes:
            - .:/api
        links:
            - "db:mongotp6"
    
    db:
        image: mongo
        ports:
            - "27017:27017"